### ISSUE TITLE
Linux instructions

### ISSUE THREAD

**Issue by kauedg** [SkyNet3D/anet-board#10]
Please add instructions on how to install this on Linux.

The "anet" folder should go in
`/home/username/Arduino/hardware`

**Comment by flamablecharlie** [comment]
I just tried this, and it doesn't work, sadly.

**Comment by jcress** [comment]
i've copied the anet directory to ~/.arduino/hardware , ~/Arduino/hardware an /usr/share/arduino/hardware  and the anet option never shows up under tools -> boards

EDIT: THis was user error.  If you're experiencing this issue, it might be because you (like me) installed arduino from APT.  Don't do this.  Follow the instructions and install version 1.8 as directed.

**Comment by Clemtaur** [comment]
Running Arduino 1.8.6  under Linux Mint 'Tara' I get:

Could not find boards.txt in /home/clemtaur/arduino-1.8.6/hardware/anet-board-master/hardware. Is it pre-1.5?
WARNING: Error loading hardware folder /home/clemtaur/arduino-1.8.6/hardware/anet-board-master
  No valid hardware definitions found in folder anet-board-master.
???

edit:  my bad.  dragged the anet folder out of the subdirectory..   ..and the >tools >boards menu has both options now..    :)
